### PR TITLE
Fix terminal show special characters on Windows

### PR DESCRIPTION
**Pull request by quycao**
When debug python on Windows OS, the terminal show output (by python print() command) that contain some special characters like this:

[0m[0Khello world[0K[?25l
[0K[?25h

### CODE REVIEW

**Comment by daveleroy** [comment]
I think this should be handled more generically and all ansi escape sequences should be stripped.

Something like.

```# from https://stackoverflow.com/questions/14693701/how-can-i-remove-the-ansi-escape-sequences-from-a-string-in-python
# 7-bit C1 ANSI sequences
ansi_escape = re.compile(r'''
\x1B    # ESC
[@-_]   # 7-bit C1 Fe
[0-?]*  # Parameter bytes
[ -/]*  # Intermediate bytes
[@-~]   # Final byte
''')```
...
```
line = self.process.read()
if not line:
	core.log_info("Nothing to read from process, closing")
	break

line = ansi_escape.sub('', line)
core.call_soon_threadsafe(callback, line)
```

This isn't perfect since read doesn't actually read a line so its possible for some sequences to be split but its probably good enough.

By the way I wouldn't actually use "integratedTerminal" and instead "internalConsole" unless you actually need program input. The integrated terminal was just kind of thrown in.

**Comment by quycao** [comment]
Thanks for your reply! I try your suggestions and have some

**Comment by daveleroy** [comment]
try adding this to the configuration
```"debugOptions" : {
	"RedirectOutput": true,
}```

**Comment by quycao** [comment]
It work perfect. Thank you!

**Pull request closed without merging**
